In [1]:
import pandas as pd
import numpy as np
import re
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
%matplotlib inline

In [2]:
file1 = r"C:\Users\Mr. Jarvis\Desktop\python project\project 3\counterfeit_train.csv"

In [3]:
file1

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 3\\counterfeit_train.csv'

In [4]:
file2 = r"C:\Users\Mr. Jarvis\Desktop\python project\project 3\counterfeit_test.csv"

In [5]:
file2

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 3\\counterfeit_test.csv'

In [6]:
c_train = pd.read_csv(file1)

In [7]:
c_test = pd.read_csv(file2)

In [8]:
c_train

Medicine_ID  Counterfeit_Weight DistArea_ID  Active_Since  Medicine_MRP  \
0          RRA15              13.100     Area046          1995      160.2366   
1          YVV26                 NaN     Area027          1983      110.4384   
2          LJC15               9.025     Area046          1995      259.4092   
3          GWC40              11.800     Area046          1995       99.9830   
4          QMN13                 NaN     Area019          1983       56.4402   
...          ...                 ...         ...           ...           ...   
6813       OYN80               8.535     Area046          1995      204.1452   
6814       ACW12              20.650     Area046          1995      235.1088   
6815       OPM10              20.000     Area017          2005      193.6292   
6816       SLY12              10.180     Area045          2000      162.8682   
6817       ATT10               7.930     Area018          2007      177.5500   

           Medicine_Type SidEffect_Level  Availability_rating  \
0           Antimalarial        critical             0.070422   
1            Mstablizers            mild             0.013000   
2                Cardiac            mild             0.060783   
3     OralContraceptives            mild             0.065555   
4          Hreplacements        critical             0.248859   
...                  ...             ...                  ...   
6813       Hreplacements            mild             0.112963   
6814       Hreplacements            mild             0.131103   
6815        Antimalarial        critical             0.105096   
6816             Statins            mild             0.099957   
6817         Mstablizers        critical             0.117445   

               Area_Type Area_City_Type Area_dist_level  Counterfeit_Sales  
0               DownTown         Tier 1           Small          1775.5026  
1             CityLimits         Tier 3          Medium          3069.1520  
2               DownTown         Tier 1           Small          2603.0920  
3               DownTown         Tier 1           Small          1101.7130  
4     MidTownResidential         Tier 1           Small           158.9402  
...                  ...            ...             ...                ...  
6813            DownTown         Tier 1           Small          2070.4520  
6814            DownTown         Tier 1           Small          2126.3792  
6815            DownTown         Tier 2         Unknown          2119.7212  
6816            DownTown         Tier 2         Unknown          1485.2138  
6817          Industrial         Tier 3          Medium          1943.9500  

[6818 rows x 12 columns]

In [9]:
c_test

Medicine_ID  Counterfeit_Weight DistArea_ID  Active_Since  Medicine_MRP  \
0          HLZ81                 NaN     Area027          1983       85.5328   
1          ECE94               13.45     Area045          2000      257.1460   
2          SAD14                7.10     Area045          2000       98.1172   
3          EQV63               18.30     Area010          1996      135.3730   
4          AIR10                 NaN     Area019          1983      112.8016   
...          ...                 ...         ...           ...           ...   
1700       KXW10                 NaN     Area027          1983      136.5704   
1701       CKE54               21.30     Area035          2002       57.0744   
1702       HAY13               20.40     Area017          2005      182.7422   
1703       ZEE32               20.00     Area018          2007      266.9672   
1704       NDL93                8.08     Area045          2000      238.7694   

           Medicine_Type SidEffect_Level  Availability_rating  \
0            Antibiotics            mild             0.112747   
1     OralContraceptives            mild             0.144446   
2           Antipyretics            mild             0.144221   
3          Tranquilizers            mild             0.100388   
4     OralContraceptives            mild             0.022585   
...                  ...             ...                  ...   
1700       Hreplacements            mild             0.050505   
1701         Antibiotics        critical             0.041118   
1702         Antiseptics            mild             0.191273   
1703       Hreplacements            mild             0.013000   
1704         Antibiotics        critical             0.098982   

               Area_Type Area_City_Type Area_dist_level  
0             CityLimits         Tier 3          Medium  
1               DownTown         Tier 2         Unknown  
2               DownTown         Tier 2         Unknown  
3     MidTownResidential         Tier 3         Unknown  
4     MidTownResidential         Tier 1           Small  
...                  ...            ...             ...  
1700          CityLimits         Tier 3          Medium  
1701            DownTown         Tier 2           Small  
1702            DownTown         Tier 2         Unknown  
1703          Industrial         Tier 3          Medium  
1704            DownTown         Tier 2         Unknown  

[1705 rows x 11 columns]

In [10]:
c_train.shape

(6818, 12)

In [11]:
c_test.shape

(1705, 11)

In [12]:
list_coloums = list(c_train.columns.values)

In [13]:
list_coloums

['Medicine_ID',
 'Counterfeit_Weight',
 'DistArea_ID',
 'Active_Since',
 'Medicine_MRP',
 'Medicine_Type',
 'SidEffect_Level',
 'Availability_rating',
 'Area_Type',
 'Area_City_Type',
 'Area_dist_level',
 'Counterfeit_Sales']

In [14]:
c_test['Counterfeit_Sales'] = pd.Series([0]* len(c_test['Medicine_ID']))

In [15]:
c_train['data'] = pd.Series(['train']*len(c_train['Medicine_ID']))

In [16]:
c_test['data'] = pd.Series(['test']*len(c_test['Medicine_ID']))

In [17]:
c_train = pd.DataFrame(data = c_train)

In [18]:
c_test = pd.DataFrame(data = c_test)

In [19]:
All_data = c_train.append(c_test)

In [20]:
All_data

Medicine_ID  Counterfeit_Weight DistArea_ID  Active_Since  Medicine_MRP  \
0          RRA15              13.100     Area046          1995      160.2366   
1          YVV26                 NaN     Area027          1983      110.4384   
2          LJC15               9.025     Area046          1995      259.4092   
3          GWC40              11.800     Area046          1995       99.9830   
4          QMN13                 NaN     Area019          1983       56.4402   
...          ...                 ...         ...           ...           ...   
1700       KXW10                 NaN     Area027          1983      136.5704   
1701       CKE54              21.300     Area035          2002       57.0744   
1702       HAY13              20.400     Area017          2005      182.7422   
1703       ZEE32              20.000     Area018          2007      266.9672   
1704       NDL93               8.080     Area045          2000      238.7694   

           Medicine_Type SidEffect_Level  Availability_rating  \
0           Antimalarial        critical             0.070422   
1            Mstablizers            mild             0.013000   
2                Cardiac            mild             0.060783   
3     OralContraceptives            mild             0.065555   
4          Hreplacements        critical             0.248859   
...                  ...             ...                  ...   
1700       Hreplacements            mild             0.050505   
1701         Antibiotics        critical             0.041118   
1702         Antiseptics            mild             0.191273   
1703       Hreplacements            mild             0.013000   
1704         Antibiotics        critical             0.098982   

               Area_Type Area_City_Type Area_dist_level  Counterfeit_Sales  \
0               DownTown         Tier 1           Small          1775.5026   
1             CityLimits         Tier 3          Medium          3069.1520   
2               DownTown         Tier 1           Small          2603.0920   
3               DownTown         Tier 1           Small          1101.7130   
4     MidTownResidential         Tier 1           Small           158.9402   
...                  ...            ...             ...                ...   
1700          CityLimits         Tier 3          Medium             0.0000   
1701            DownTown         Tier 2           Small             0.0000   
1702            DownTown         Tier 2         Unknown             0.0000   
1703          Industrial         Tier 3          Medium             0.0000   
1704            DownTown         Tier 2         Unknown             0.0000   

       data  
0     train  
1     train  
2     train  
3     train  
4     train  
...     ...  
1700   test  
1701   test  
1702   test  
1703   test  
1704   test  

[8523 rows x 13 columns]

In [21]:
All_data.dtypes

Medicine_ID             object
Counterfeit_Weight     float64
DistArea_ID             object
Active_Since             int64
Medicine_MRP           float64
Medicine_Type           object
SidEffect_Level         object
Availability_rating    float64
Area_Type               object
Area_City_Type          object
Area_dist_level         object
Counterfeit_Sales      float64
data                    object
dtype: object

In [22]:
All_data.isnull().sum()

Medicine_ID               0
Counterfeit_Weight     1463
DistArea_ID               0
Active_Since              0
Medicine_MRP              0
Medicine_Type             0
SidEffect_Level           0
Availability_rating       0
Area_Type                 0
Area_City_Type            0
Area_dist_level           0
Counterfeit_Sales         0
data                      0
dtype: int64

In [24]:
Mean_value = All_data["Counterfeit_Weight"].mean()

In [25]:
Mean_value

14.15764518413612

In [26]:
All_data['Counterfeit_Weight'] = All_data['Counterfeit_Weight'].fillna(Mean_value)

In [27]:
All_data.isnull().sum()

Medicine_ID            0
Counterfeit_Weight     0
DistArea_ID            0
Active_Since           0
Medicine_MRP           0
Medicine_Type          0
SidEffect_Level        0
Availability_rating    0
Area_Type              0
Area_City_Type         0
Area_dist_level        0
Counterfeit_Sales      0
data                   0
dtype: int64

In [28]:
All_data['DistArea_ID'].value_counts()

Area027    935
Area013    932
Area049    930
Area035    930
Area046    930
Area045    929
Area018    928
Area017    926
Area010    555
Area019    528
Name: DistArea_ID, dtype: int64

In [29]:
All_data.dtypes

Medicine_ID             object
Counterfeit_Weight     float64
DistArea_ID             object
Active_Since             int64
Medicine_MRP           float64
Medicine_Type           object
SidEffect_Level         object
Availability_rating    float64
Area_Type               object
Area_City_Type          object
Area_dist_level         object
Counterfeit_Sales      float64
data                    object
dtype: object

In [34]:
cat_cols = All_data.select_dtypes(["object"]).columns

In [35]:
cat_cols

Index(['Medicine_ID', 'DistArea_ID', 'Medicine_Type', 'SidEffect_Level',
       'Area_Type', 'Area_City_Type', 'Area_dist_level', 'data'],
      dtype='object')

In [36]:
for col in ['Medicine_Type','SidEffect_Level','Area_Type','Area_City_Type','Area_dist_level']:
    
    freq = All_data[col].value_counts()
    select_catgory = freq.index[freq> 1][:-1]
    
    print(col)
    
    for cat in select_catgory:
        name = col+'_'+str(cat)
        All_data[name] = (All_data[col]== cat).astype(int)
    del All_data[col]

Medicine_Type
SidEffect_Level
Area_Type
Area_City_Type
Area_dist_level


In [37]:
All_data = All_data.drop(['DistArea_ID','Active_Since'],1)

In [38]:
All_data.shape

(8523, 30)

In [39]:
c_train = All_data.iloc[0:6818,]

In [40]:
c_train.shape

(6818, 30)

In [41]:
c_test = All_data.iloc[6818:,]

In [42]:
c_test.shape

(1705, 30)

In [43]:
c_train = c_train.drop(['data'],1)

In [44]:
c_train.shape

(6818, 29)

In [45]:
c_test = c_test.drop(['data'],1)

In [46]:
c_test = c_test.drop(['Counterfeit_Sales'],1)

In [47]:
c_test.shape

(1705, 28)

In [48]:
c_train = c_train.drop(['Medicine_ID'],1)

In [49]:
x = c_train.drop(['Counterfeit_Sales'],1)

In [50]:
y = c_train['Counterfeit_Sales']

In [51]:
x.shape

(6818, 27)

In [52]:
y.shape

(6818,)

In [53]:
training , testing = train_test_split(c_train , test_size = 0.2 , random_state = 2)

In [54]:
training.shape

(5454, 28)

In [55]:
testing.shape

(1364, 28)

In [56]:
x_train = training.drop(['Counterfeit_Sales'],1)

In [57]:
x_train.shape

(5454, 27)

In [58]:
y_train = training['Counterfeit_Sales']

In [59]:
y_train.shape

(5454,)

In [60]:
x_test = testing.drop(['Counterfeit_Sales'],1)

In [61]:
x_test.shape

(1364, 27)

In [62]:
y_test = testing['Counterfeit_Sales']

In [63]:
y_test.shape

(1364,)

In [67]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
import math
import time

In [77]:
linear = LinearRegression(n_jobs=1)

In [78]:
linear

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [79]:
linear.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [81]:
 import statsmodels.api as sm

In [82]:
model = sm.OLS(y_train, x_train).fit()

In [83]:
model_predict = model.predict(x_test)

In [84]:
model_predict

5443     962.647824
4972     776.919545
3383    3889.434371
1350    3650.140505
145     1186.312480
           ...     
1058    1872.553253
5841    1587.938764
6517    1743.249694
6135    3901.321024
1123    1713.256154
Length: 1364, dtype: float64

In [85]:
model

In [86]:
final_model = sm.OLS(y, x).fit()

In [87]:
final_model

In [88]:
predicted = linear.predict(x_test)

In [89]:
predicted

array([ 958.65121022,  769.25937195, 3889.21868148, ..., 1743.55943103,
       3906.05077898, 1707.77496645])

In [90]:
predicted.shape

(1364,)

In [91]:
residual = model_predict - y_test

In [92]:
MAE = abs(sum(residual))/len(y_test)

In [93]:
MAE

16.86155900077899

In [94]:
1-(MAE/1660)

0.9898424343368801

In [95]:
round(1-(MAE/1660) , 2)

0.99

In [96]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [98]:
vif = pd.DataFrame()

In [99]:
vif["VIF Factor"] = [variance_inflation_factor(x_train.values, i) for i in range(x_train.shape[1])]
vif["features"] = x_train.columns

In [100]:
vif

VIF Factor                          features
0    12.006790                Counterfeit_Weight
1     6.898091                      Medicine_MRP
2     3.613639               Availability_rating
3    13.431147         Medicine_Type_Antibiotics
4    13.624305       Medicine_Type_Hreplacements
5    10.317401         Medicine_Type_Antiseptics
6     9.862141  Medicine_Type_OralContraceptives
7     7.995949        Medicine_Type_Antipyretics
8     7.464918             Medicine_Type_Cardiac
9     7.702654         Medicine_Type_Mstablizers
10    6.368611       Medicine_Type_Tranquilizers
11    5.713194          Medicine_Type_Analgesics
12    5.450825        Medicine_Type_Antimalarial
13    3.733178            Medicine_Type_Antacids
14    3.134652             Medicine_Type_Statins
15    2.661541     Medicine_Type_MuscleRelaxants
16    2.318526          Medicine_Type_Antifungal
17    2.142866          Medicine_Type_Stimulants
18    3.403840              SidEffect_Level_mild
19   20.802302                Area_Type_DownTown
20    5.535707      Area_Type_MidTownResidential
21    1.971907              Area_Type_CityLimits
22    9.190728             Area_City_Type_Tier 3
23    5.610094             Area_City_Type_Tier 2
24   10.175005            Area_dist_level_Medium
25    9.965807           Area_dist_level_Unknown
26   10.325262             Area_dist_level_Small

In [101]:
ridge = Ridge(fit_intercept=True)

In [102]:
x_train.shape[1]

27

In [103]:
ridge.fit(x_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [104]:
predicted_ridge = ridge.predict(x_test)

In [105]:
predicted_ridge

array([ 958.55622869,  769.74596912, 3890.21671847, ..., 1746.07737653,
       3907.23142359, 1711.52317353])

In [106]:
residual_ridge = predicted_ridge - y_test

In [107]:
MAE = abs(sum(residual_ridge))/len(y_test)

In [108]:
MAE

17.491259890875437

In [109]:
1-(MAE/1660)

0.9894630964512798

In [110]:
lasso = Lasso(fit_intercept=True)

In [111]:
lasso.fit(x_train,y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [112]:
prediction_lasso = lasso.predict(x_test)

In [113]:
prediction_lasso

array([ 975.14731845,  796.80622693, 3889.7876595 , ..., 1802.57160688,
       3875.0910978 , 1691.39084235])

In [114]:
residual_lasso = prediction_lasso - y_test

In [115]:
MAE = abs(sum(residual_lasso))/len(y_test)

In [116]:
MAE

17.562275652207607

In [117]:
1-(MAE/1660)

0.9894203158721641

In [118]:
final_ridge = ridge.fit(x,y)

In [119]:
c_test = c_test.drop(['Medicine_ID'],1)

In [120]:
final_prediction1 = final_model.predict(c_test)

In [121]:
final_prediction1

0       2798.983855
1       4010.112585
2       1518.090174
3        136.477158
4        -98.250213
           ...     
1700    3553.218431
1701    1086.566864
1702    2809.593055
1703    3878.896092
1704    3839.218946
Length: 1705, dtype: float64

In [122]:
final_prediction = final_ridge.predict(c_test)

In [123]:
final_prediction

array([2798.00884424, 4010.89172525, 1513.25442903, ..., 2812.24505506,
       3878.55149768, 3834.29841936])

In [124]:
final_prediction.shape

(1705,)

In [125]:
c_test1 = All_data.iloc[6818:,]

In [126]:
final_solution = pd.DataFrame(list(zip(c_test1['Medicine_ID'],list(final_prediction))),
                     columns=['Medicine_ID','Counterfeit_Sales'])

In [127]:
final_solution

Medicine_ID  Counterfeit_Sales
0          HLZ81        2798.008844
1          ECE94        4010.891725
2          SAD14        1513.254429
3          EQV63         155.068056
4          AIR10        -113.989943
...          ...                ...
1700       KXW10        3550.993147
1701       CKE54        1095.896715
1702       HAY13        2812.245055
1703       ZEE32        3878.551498
1704       NDL93        3834.298419

[1705 rows x 2 columns]

In [128]:
pd.DataFrame(final_solution).to_csv("NITESH_BHOSLE_P3_part2_second_method.csv",index=False)